package promhs;

import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20103295 Ni Putu Eka Sepiantini
 */
public class frmtest extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    static ResultSet rs;
    static Statement stmt;
    dbkoneksi cnn = new dbkoneksi();
    loadIMG img = new loadIMG();
    
    public frmtest() {
        initComponents();
        this.initTable();
        this.getdata();
    }
    
    private void initTable(){
        model = new DefaultTableModel();
        Tdsn.setModel(model);
        model.addColumn("NID");
        model.addColumn("Nama Dosen");
        model.addColumn("Tgl Lahir");
        model.addColumn("Mata Kuliah");
        model.addColumn("Jenis Kelamin");
    }
    
    private void tampildata(String sql){
        try{
            Statement stmt = cnn.koneksi().createStatement();
            this.rs = stmt.executeQuery(sql);
        }catch(Exception e){
            System.out.println("Terjadi kendala pada query");
        }
    }
    
    private void getdata(){
        String sql = " Select NID, NAMA, TGLLAHIR, MATKUL, JK FROM dsn;";
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            this.tampildata(sql);
            while(this.rs.next()){
                Object[] obj = new Object[5];
                obj[0] = this.rs.getString("NID");
                obj[1] = this.rs.getString("NAMA");
                obj[2] = this.rs.getString("TGLLAHIR");
                obj[3] = this.rs.getString("MATKUL");
                String txJK = this.rs.getString("jk");
                if(txJK.equals("L")){
                    obj[4] = "Laki - laki";
                }else{
                    obj[4] = "Perempuan ";
                }
                model.addRow(obj);
            }
        }catch(Exception e){
                
        }
    }
    
        private boolean UpdateData(String SQL){
            boolean hsl = false;
            try{
                Statement stmt = cnn.koneksi().createStatement();
                stmt.executeUpdate(SQL);
                hsl = true;
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Terjadi Kendala Pada Instruksi");
            }
        return hsl;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tdsn = new javax.swing.JTable();
        cmdbaru = new javax.swing.JButton();
        lbCURD = new javax.swing.JLabel();
        IMGPHOTO = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txNID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txNAMA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txTGL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txJKL = new javax.swing.JRadioButton();
        txJKP = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txMK = new javax.swing.JComboBox<>();
        cmdupdate = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdbatal = new javax.swing.JButton();
        cmdclose = new javax.swing.JButton();
        cmdstore = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("List Data Dosen ");

        Tdsn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tdsn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TdsnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tdsn);

        cmdbaru.setText("Data Baru");
        cmdbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbaruActionPerformed(evt);
            }
        });

        lbCURD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbCURD.setText("Detail");

        IMGPHOTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/v.jpg"))); // NOI18N

        jLabel4.setText("NID");

        txNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIDActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Dosen");

        txNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNAMAActionPerformed(evt);
            }
        });

        jLabel3.setText("Tgl Lahir");

        txTGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTGLActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenis Kelamin");

        txJKL.setText("Laki - laki");

        txJKP.setText("Perempuan");
        txJKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJKPActionPerformed(evt);
            }
        });

        jLabel7.setText("Mata Kuliah");

        txMK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Mata Kuliah", "Object Oriented Programming", "Perpajakan", "Mobile Proggraming", "Akuntansi Biaya", "Analisa dan Desain Sistem Informasi", "e-Business", "Struktur Data", "" }));

        cmdupdate.setText("Update Data");
        cmdupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdupdateActionPerformed(evt);
            }
        });

        cmdhapus.setText("Hapus Data");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdbatal.setText("Batal");
        cmdbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbatalActionPerformed(evt);
            }
        });

        cmdclose.setText("Tutup Form");
        cmdclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcloseActionPerformed(evt);
            }
        });

        cmdstore.setText("Simpan Data");
        cmdstore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdstoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbCURD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IMGPHOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txNID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txNAMA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(txJKL))
                                .addGap(18, 18, 18)
                                .addComponent(txJKP))
                            .addComponent(jLabel7)
                            .addComponent(txMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdstore, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdupdate)
                        .addGap(18, 18, 18)
                        .addComponent(cmdhapus)
                        .addGap(83, 266, Short.MAX_VALUE)
                        .addComponent(cmdbatal)
                        .addGap(18, 18, 18)
                        .addComponent(cmdclose))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmdbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbCURD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IMGPHOTO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txJKL)
                                    .addComponent(txJKP))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdstore)
                    .addComponent(cmdupdate)
                    .addComponent(cmdhapus)
                    .addComponent(cmdbatal)
                    .addComponent(cmdclose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TdsnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TdsnMouseClicked
        String urlGambarNull = "src/img/gambar.jpg";
        this.txNID.setText( model.getValueAt(Tdsn.getSelectedRow(), 0).toString());
        this.txNAMA.setText( model.getValueAt(Tdsn.getSelectedRow(), 1).toString());
        this.txTGL.setText( model.getValueAt(Tdsn.getSelectedRow(), 2).toString());
        this.txMK.setSelectedItem(model.getValueAt(Tdsn.getSelectedRow(), 3).toString());
        String txJK = model.getValueAt(Tdsn.getSelectedRow(), 4).toString();
        if(txJK.equals("Perempuan")){
            this.txJKP.setSelected(true);
        }else{
            this.txJKL.setSelected(true);
        }
        String urlGambar = "src/img/"+this.txNID.getText() + ".jpg";
        BufferedImage loadImg = img.loadImage(urlGambar);
        if(loadImg == null){
            loadImg = img.loadImage(urlGambarNull);
        }
        ImageIcon imageIcon = new ImageIcon(loadImg);
        this.IMGPHOTO.setIcon(imageIcon);

        this.lbCURD.setText("Edit Data "+this.txNID.getText());
        this.cmdstore.setEnabled(false);
        this.cmdupdate.setEnabled(true);
        this.cmdhapus.setEnabled(true);
    }//GEN-LAST:event_TdsnMouseClicked

    private void cmdbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbaruActionPerformed
        this.cmdbaru.setEnabled(false);
        this.cmdupdate.setEnabled(false);
        this.cmdhapus.setEnabled(false);
        this.cmdclose.setEnabled(false);
        this.cmdstore.setVisible(true);
        this.cmdbatal.setVisible(true);

        this.txNID.setText("");
        this.txNAMA.setText("");
        this.txTGL.setText("");
        this.txMK.setSelectedIndex(0);
    }//GEN-LAST:event_cmdbaruActionPerformed

    private void txNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIDActionPerformed

    private void txNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNAMAActionPerformed

    private void txTGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTGLActionPerformed

    private void txJKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJKPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJKPActionPerformed

    private void cmdupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdupdateActionPerformed
        String NID = this.txNID.getText();
        String NAMA = this.txNAMA.getText();
        String TGL = this.txTGL.getText();
        String MATKUL = this.txMK.getSelectedItem().toString();
        String JKEL = "L";
        if(this.txJKP.isSelected()){
            JKEL = "P";
        }
        String SQLUpdate = "UPDATE dsn SET NAMA='"+NAMA+"', MATKUL='"+MATKUL+"', JK='"+JKEL+"', TGLLAHIR='"+TGL+"' WHERE NID='"+NID+"';";
        if(this.UpdateData(SQLUpdate)){
            this.getdata();
            JOptionPane.showMessageDialog(null,"data telah di Update");
        }
    }//GEN-LAST:event_cmdupdateActionPerformed

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed
        String NID = this.txNID.getText();
        String NAMA = this.txNAMA.getText();

        int opsi = JOptionPane.showConfirmDialog(null, "Yakin Akan Menghapus Data dari "+NAMA+"("+NID+")?","Konfirmasi", JOptionPane.YES_NO_OPTION );
        if(opsi == JOptionPane.YES_OPTION ){
            String SQLDelete = "DELETE FROM mhs WHERE NID = '"+NID+"';";
            if(this.UpdateData(SQLDelete)){
                this.getdata();
                JOptionPane.showMessageDialog(null, "Data Telah Terhapus");
            }
        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbatalActionPerformed
        this.cmdclose.setEnabled(true);
        this.cmdbaru.setEnabled(true);
        this.cmdstore.setEnabled(false);
        this.cmdbatal.setVisible(false);
    }//GEN-LAST:event_cmdbatalActionPerformed

    private void cmdcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdcloseActionPerformed

    private void cmdstoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdstoreActionPerformed
        String NID = this.txNID.getText();
        String NAMA = this.txNAMA.getText();
        String TGL = this.txTGL.getText();
        String MATKUL = this.txMK.getSelectedItem().toString();
        String JKEL = "L";
        if(this.txJKP.isSelected()){
            JKEL = "P";
        }
        String SQLInsert = "INSERT INTO dsn(NID,NAMA,MATKUL,JK,TGLLAHIR) VALUES('"+NID+"','"+NAMA+"','"+MATKUL+"','"+JKEL+"','"+TGL+"');";
        if(this.UpdateData(SQLInsert)){
            this.getdata();
            JOptionPane.showMessageDialog(null, "Data telah di Tambahkan");
        }
        this.cmdstore.setEnabled(false);
        this.cmdbatal.setVisible(false);
        this.cmdclose.setEnabled(true);
        this.cmdbaru.setEnabled(true);
    }//GEN-LAST:event_cmdstoreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMGPHOTO;
    private javax.swing.JTable Tdsn;
    private javax.swing.JButton cmdbaru;
    private javax.swing.JButton cmdbatal;
    private javax.swing.JButton cmdclose;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdstore;
    private javax.swing.JButton cmdupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCURD;
    private javax.swing.JRadioButton txJKL;
    private javax.swing.JRadioButton txJKP;
    private javax.swing.JComboBox<String> txMK;
    private javax.swing.JTextField txNAMA;
    private javax.swing.JTextField txNID;
    private javax.swing.JTextField txTGL;
    // End of variables declaration//GEN-END:variables
}
